# Generated by Django 3.2.8 on 2021-10-10 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0002_rename_itensdopedido_itemdopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
    ]
