# Generated by Django 3.2.8 on 2021-10-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_venda_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='venda',
            name='nfe_emitidade',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItensDoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.venda')),
            ],
        ),
    ]
