# Generated by Django 3.2.8 on 2021-10-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20211009_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itensdopedido',
            old_name='produtos',
            new_name='produto',
        ),
    ]
