# Generated by Django 3.2.8 on 2021-10-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_rename_produtos_itensdopedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
